


/*******************************************
View designed to execute on another database
via utility procedure RunViewOnDatabase
********************************************/
CREATE VIEW [SqlSyncInternal].[vwMetaDataQuery] AS
--RunViewOnDatabase
SELECT CONVERT(NVARCHAR(MAX),(
SELECT
	C.TABLE_SCHEMA AS SCH, C.TABLE_NAME AS TAB, C.COLUMN_NAME AS COL, C.DATA_TYPE AS TYP, C.ORDINAL_POSITION AS ORD
	,COLUMNPROPERTY (OBJECT_ID(C.TABLE_SCHEMA+'.'+C.TABLE_NAME),C.COLUMN_NAME, 'IsComputed') | 
	 COLUMNPROPERTY (OBJECT_ID(C.TABLE_SCHEMA+'.'+C.TABLE_NAME),C.COLUMN_NAME, 'IsColumnSet') |
		CASE WHEN C.DATA_TYPE = 'timestamp' THEN 1 ELSE 0 END AS COM
	,ISNULL(PK.isPK,0) AS PK
	,COLUMNPROPERTY(OBJECT_ID(C.TABLE_SCHEMA+'.'+C.TABLE_NAME),C.COLUMN_NAME,'IsIdentity') AS IDN
FROM INFORMATION_SCHEMA.COLUMNS C
JOIN INFORMATION_SCHEMA.TABLES T ON T.TABLE_NAME=C.TABLE_NAME AND T.TABLE_SCHEMA=C.TABLE_SCHEMA
OUTER APPLY (
	SELECT 1 AS IsPK
	FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS TC
	JOIN INFORMATION_SCHEMA.KEY_COLUMN_USAGE KC ON KC.TABLE_SCHEMA=TC.TABLE_SCHEMA AND KC.TABLE_NAME=TC.TABLE_NAME
		AND KC.CONSTRAINT_NAME = TC.CONSTRAINT_NAME AND KC.COLUMN_NAME=C.COLUMN_NAME
	WHERE TC.CONSTRAINT_TYPE='PRIMARY KEY' AND TC.TABLE_SCHEMA=C.TABLE_SCHEMA AND  TC.TABLE_NAME=C.TABLE_NAME) AS PK
WHERE T.TABLE_TYPE='BASE TABLE'
FOR XML PATH('C'))) AS XML

